#spring:
#  # SecurityProperties
#  security:
#    # InMemoryUserDetailsManager
#    user:
#      name: antony
#      password: liferay
#      roles: admin

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/security?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: liferay
server:
  servlet:
    session:
      timeout: 5m